version: '3'
services:
  stac:
    container_name: stac-fastapi-pgstac
    platform: linux/amd64
    build:
      context: ./stac-fastapi-pgstac
    environment:
      - APP_HOST=0.0.0.0
      - APP_PORT=8082
      - RELOAD=true
      - ENVIRONMENT=local
      - POSTGRES_USER=username
      - POSTGRES_PASS=password
      - POSTGRES_DBNAME=postgis
      - POSTGRES_HOST_READER=database
      - POSTGRES_HOST_WRITER=database
      - POSTGRES_PORT=5432
      - WEB_CONCURRENCY=10
      - VSI_CACHE=TRUE
      - GDAL_HTTP_MERGE_CONSECUTIVE_RANGES=YES
      - GDAL_DISABLE_READDIR_ON_OPEN=EMPTY_DIR
      - DB_MIN_CONN_SIZE=1
      - DB_MAX_CONN_SIZE=1
      - USE_API_HYDRATE=${USE_API_HYDRATE:-false}

    labels:
    - "traefik.enable=true"
    - "traefik.http.middlewares.compresstraefik.compress=true"

    - "traefik.http.routers.public_collections.rule=Host(`${APP_HOST}`) && Path(`/api`) || Path(`/api.html`) || Path(`/`) || Path(`/conformance`) || Path(`/collections`) || Path(`/search`) || Path(`/queryables`) || Path(`/_mgmt/ping`)"
    - "traefik.http.routers.public_collections.priority=1"
    - 'traefik.http.routers.public_collections.tls=true'
    - "traefik.http.routers.public_collections.tls.certresolver=letsencrypt"
    - "traefik.http.routers.public_collections.entrypoints=websecure"
    - "traefik.http.routers.public_collections.service=public_stac"
    - "traefik.http.services.public_stac.loadbalancer.server.port=8082"

    - "traefik.http.routers.authenticated_collections.rule=Host(`${APP_HOST}`) && (Path(`/collections`) && Method(`POST`) || Method(`PUT`) || Method(`DELETE`)) || (Path(`/search`) && Method(`POST`))"
    - "traefik.http.routers.authenticated_collections.priority=10000"
    - 'traefik.http.routers.authenticated_collections.tls=true'
    - "traefik.http.routers.authenticated_collections.tls.certresolver=letsencrypt"
    - "traefik.http.routers.authenticated_collections.entrypoints=websecure"
    - "traefik.http.routers.authenticated_collections.service=authenticated_stac"
    - "traefik.http.services.authenticated_stac.loadbalancer.server.port=8082"
    - "traefik.http.services.authenticated_stac.loadbalancer.passhostheader=true"
    - "traefik.http.routers.authenticated_collections.middlewares=keycloakAuth@file"
    
    volumes:
      - ./stac-fastapi-pgstac:/app

    depends_on:
      - database
    networks:
      - stac-network
    command: bash -c "./scripts/wait-for-it.sh database:5432 && python -m stac_fastapi.pgstac.app"

  database:
    container_name: stac-db
    image: ghcr.io/stac-utils/pgstac:v0.7.10
    environment:
      - POSTGRES_USER=username
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=postgis
      - PGUSER=username
      - PGPASSWORD=password
      - PGDATABASE=postgis
    volumes:
      - ./pg-data:/var/lib/postgresql
    labels:
      - "traefik.enable=false"
    networks:
      - stac-network
    ports:
      - "5439:5432"
    command: postgres -N 500

networks:
  stac-network:
    driver: bridge
