version: "3"

services:
  keyval:
    container_name: keyval
    build:
      context: ./keyval
      # target: dev
      target: prod
    # ports:
    #   - 5000:5000
    # volumes:
    #   - ./:/app
    labels:
      - "traefik.enable=true"
    networks:
      - stac-network
    env_file:
      - ./.env

networks:
  stac-network:
    driver: bridge